package constants

var FieldsToMap = map[string][]string{
	"MovingObjectPosition$MovingObjectType": {"BLOCK"},
	"ActiveRenderInfo":                      {"modelview", "projection"},
	"NetHandlerPlayClient":                  {"netManager"},
	"MovingObjectPosition":                  {"entityHit", "typeOfHit", "hitVec"},
	"S27PacketExplosion":                    {"field_149152_f", "field_149153_g", "field_149159_h"},
	"S18PacketEntityTeleport":               {"field_149456_b", "field_149454_d"},
	"S12PacketEntityVelocity":               {"field_149415_b", "field_149416_c", "field_149414_d", "field_149417_a"},
	"EntityLivingBase":                      {"hurtTime", "jumpTicks", "limbSwing", "limbSwingAmount", "prevLimbSwingAmount", "renderYawOffset", "prevRenderYawOffset", "rotationYawHead", "prevRotationYawHead", "moveStrafing"},
	"AbstractClientPlayer":                  {"locationOfCape"},
	"C02PacketUseEntity":                    {"entityId", "action"},
	"C02PacketUseEntity$Action":             {"ATTACK"},
	"Minecraft":                             {"thePlayer", "theWorld", "timer", "mouseHelper", "gameSettings", "playerController", "inGameHasFocus", "leftClickCounter", "rightClickDelayTimer", "objectMouseOver", "currentScreen", "renderEngine", "instance"},
	"GameSettings":                          {"ofFastRender", "mouseSensitivity", "thirdPersonView", "keyBindAttack", "keyBindUseItem", "keyBindForward", "keyBindSprint", "keyBindSneak"},
	"KeyBinding":                            {"pressed", "keyCode"},
	"Vec3":                                  {"xCoord", "yCoord", "zCoord"},
	"EntityPlayer":                          {"inventoryContainer", "inventory"},
	"GuiContainer":                          {"inventorySlots"},
	"GuiChest":                              {"lowerChestInventory"},
	"Container":                             {"windowId"},
	"InventoryPlayer":                       {"currentItem", "armorInventory"},
	"ItemStack":                             {"theItem"},
	"EnumAction":                            {"block", "bow"},
	"ItemArmor":                             {"armorType", "damageReduceAmount"},
	"Enchantment":                           {"effectId", "protection", "blastProtection", "fireProtection", "thorns", "unbreaking", "projectileProtection"},
	"World":                                 {"loadedEntityList", "loadedTileEntityList"},
	"Entity":                                {"posX", "posY", "posZ", "lastTickPosX", "lastTickPosY", "lastTickPosZ", "motionX", "motionY", "motionZ", "rotationYaw", "rotationPitch", "prevRotationYaw", "prevRotationPitch", "width", "height", "boundingBox", "ticksExisted", "onGround", "inWater", "riddenByEntity", "ridingEntity", "isInWeb"},
	"AxisAlignedBB":                         {"minX", "minY", "minZ", "maxX", "maxY", "maxZ"},
	"NetworkManager":                        {"channel"},
	"Timer":                                 {"renderPartialTicks", "timerSpeed"},
	"RenderItem":                            {"zLevel"},
	"TextureManager":                        {"mapTextureObjects"},
}
